// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodaClientVSIX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCodaClientVSIXPackageString = "5ea4dc4a-e0e0-4e50-b882-6910c760a820";
        public static Guid guidCodaClientVSIXPackage = new Guid(guidCodaClientVSIXPackageString);

        public const string guidCodaClientVSIXPackageCmdSetString = "295b4466-b14f-4b33-829f-223c1c2fd69a";
        public static Guid guidCodaClientVSIXPackageCmdSet = new Guid(guidCodaClientVSIXPackageCmdSetString);

        public const string guidImagesString = "9df71024-9335-4073-95a6-b6e7b85e5e5b";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidCodaClientVSIXPackageCmdSet1String = "ca9027a9-dbcc-41de-8cf3-3f6f28faf2d3";
        public static Guid guidCodaClientVSIXPackageCmdSet1 = new Guid(guidCodaClientVSIXPackageCmdSet1String);

        public const string guidImages1String = "fd668c0a-796b-4f74-8855-ba1b9924e548";
        public static Guid guidImages1 = new Guid(guidImages1String);

        public const string guidCodaClientVSIXPackageCmdSet2String = "789a3f9f-8a8f-4914-bcf0-bb716802b854";
        public static Guid guidCodaClientVSIXPackageCmdSet2 = new Guid(guidCodaClientVSIXPackageCmdSet2String);

        public const string guidImages2String = "6633e2e4-e518-440a-8eaa-c63208f3cbd6";
        public static Guid guidImages2 = new Guid(guidImages2String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CodaToolWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
        public const int MyMenuGroup = 0x1020;
        public const int cmdidCodaAnalyzeCommand = 0x0100;
        public const int cmdidCodaConfigCommand = 0x0100;
    }
}